### ISSUE TITLE
The app crash when using this library 

### ISSUE THREAD

**Issue by SSenocico** [Henryforce/BLECombineKit#35]
Even I add this library with SPM or Carthage,
The app is crashing when the app is running on iPhone, by calling:

`let centralManager = BLECombineKit.buildCentralManager(with: CBCentralManager())`

![Screenshot 2022-02-14 at 12 03 13](https://user-images.githubusercontent.com/60232541/153843331-0e6061b6-d9f5-41c6-a796-acef4faf3c44.png)

**Comment by Henryforce** [comment]
Hello @SSenocico , the logs you are sharing seem to point that the issue is more of a linking problem. 

I have been testing the app in a physical device (iPhone 13 Pro with iOS 15.3.1) using Xcode 13.2.1 and no issues whatsoever. I am thinking that the issue might be specific to the project in which you are trying to use the app.

First, I would recommend you to try installing BLECombineKit in a simple app and run it in a physical device to make sure that your build environment is correct.

Try to run this code snippet inside a ViewController's viewDidAppear or viewDidLoad (please make sure your device's bluetooth is on) and you should see some input and no crash.
```
let manager = BLECombineKit.buildCentralManager()
        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
            manager.scanForPeripherals(withServices: nil, options: nil)
                .sink { error in
                    print(error)
                } receiveValue: { result in
                    print(result)
                }.store(in: &self.cancellables)
        }
```

Let me know of your findings.
